# Generated by Django 3.0.3 on 2020-03-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enumerator',
            fields=[
                ('enumeratorID', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='enumeratorID')),
                ('prefix', models.CharField(choices=[('MR', 'Mr'), ('MRS', 'Mrs'), ('MISS', 'Miss'), ('MS', 'MS'), ('DR', 'Dr')], max_length=10, verbose_name='prefix')),
                ('firstName', models.CharField(max_length=45, verbose_name='firstName')),
                ('lastName', models.CharField(max_length=45, verbose_name='lastName')),
                ('suffix', models.CharField(blank=True, max_length=45, verbose_name='suffix')),
                ('organization', models.CharField(blank=True, max_length=100, verbose_name='organization')),
                ('date_of_birth', models.CharField(max_length=35)),
                ('active_flag', models.BooleanField(default=True, verbose_name='active_flag')),
                ('qualifications', models.CharField(max_length=100, verbose_name='qualifications')),
                ('username', models.CharField(max_length=100, verbose_name='username')),
                ('email', models.EmailField(max_length=100, verbose_name='email')),
            ],
        ),
    ]
