# Generated by Django 3.0.3 on 2020-02-24 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enumerator',
            name='username',
            field=models.CharField(default='Default', max_length=100, verbose_name='username'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enumerator',
            name='email',
            field=models.EmailField(verbose_name='email', max_length=100),
            preserve_default=False,
        ),
    ]
