# Generated by Django 3.0.3 on 2020-02-29 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20200224_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enumerator',
            name='prefix',
            field=models.CharField(choices=[('MR', 'Mr'), ('MRS', 'Mrs'), ('MISS', 'Miss'), ('MS', 'MS'), ('DR', 'Dr')], max_length=10, verbose_name='prefix'),
        ),
    ]
