# Generated by Django 3.0.3 on 2020-03-07 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('answerID', models.AutoField(primary_key=True, serialize=False)),
                ('answerString', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('questionnaireID', models.AutoField(primary_key=True, serialize=False, verbose_name='questionnaireID')),
                ('questionnaireName', models.CharField(max_length=100, verbose_name='questionnaireName')),
                ('questionnaireVersion', models.CharField(max_length=45, verbose_name='questionnaireVersion')),
                ('active_flag', models.IntegerField(choices=[(1, 'True'), (0, 'False')], default=True, verbose_name='active_flag')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('questionTypeID', models.AutoField(primary_key=True, serialize=False, verbose_name='questionTypeID')),
                ('questionType', models.CharField(choices=[('S', 'Single'), ('M', 'Multiple'), ('T', 'Text')], max_length=10, verbose_name='questionType')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('questionID', models.AutoField(primary_key=True, serialize=False, verbose_name='questionID')),
                ('questionString', models.CharField(max_length=300, verbose_name='questionString')),
                ('answerMin', models.IntegerField(default=1, verbose_name='answer_min')),
                ('answerMax', models.IntegerField(default=1, verbose_name='answer_max')),
                ('questionInstruction', models.CharField(blank=True, max_length=300, verbose_name='QuestionInstruction')),
                ('questionMedia', models.CharField(blank=True, max_length=45)),
                ('questionTypeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questions.QuestionType', verbose_name='questionTypeID')),
                ('questionnaireID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questions.Questionnaire')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('answerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questions.Answer')),
                ('questionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questions.Questions')),
                ('questionnaireID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questions.Questionnaire')),
            ],
        ),
        migrations.CreateModel(
            name='Logic',
            fields=[
                ('logic_id', models.AutoField(primary_key=True, serialize=False)),
                ('seq_num', models.IntegerField(verbose_name='Sequence_Number')),
                ('rel_type', models.CharField(blank=True, choices=[('INSEQ', 'In Sequence'), ('NEXT', 'Next'), ('AND', 'And'), ('OR', 'Or')], max_length=10)),
                ('rel_ID', models.IntegerField(null=True, unique=True, verbose_name='relationID')),
                ('logic_questionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logic_questionID', to='Questions.Questions')),
                ('next_qID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_qID', to='Questions.Questions')),
                ('questionnaireID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questions.Questionnaire')),
                ('rel_ans_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Questions.Answer')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='questionnaireID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questions.Questionnaire'),
        ),
        migrations.CreateModel(
            name='QuestionResponse',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True, verbose_name='text')),
                ('date', models.CharField(max_length=35)),
                ('answerID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Questions.Answer')),
                ('patientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patients.Patient')),
                ('questionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questions.Questions')),
                ('questionnaireID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questions.Questionnaire')),
            ],
            options={
                'db_table': 'Response',
                'unique_together': {('patientID', 'questionID', 'answerID', 'questionnaireID', 'date')},
            },
        ),
        migrations.CreateModel(
            name='QuestionRelation',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('question_rel_questionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_rel_questionID', to='Questions.Questions')),
                ('questionnaireID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questions.Questionnaire')),
                ('rel_ID', models.ForeignKey(db_column='rel_ID', on_delete=django.db.models.deletion.CASCADE, to='Questions.Logic', to_field='rel_ID')),
                ('rel_ans_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questions.Answer')),
                ('rel_qID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_qID', to='Questions.Questions')),
            ],
            options={
                'unique_together': {('rel_ID', 'question_rel_questionID', 'rel_qID', 'rel_ans_ID', 'questionnaireID')},
            },
        ),
        migrations.CreateModel(
            name='PatientAssessment',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('questionnaireStatus', models.CharField(max_length=35)),
                ('start', models.CharField(blank=True, max_length=35)),
                ('end', models.CharField(blank=True, max_length=35)),
                ('assess_patientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patients.Patient')),
                ('assess_questionnaireID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questions.Questionnaire')),
            ],
            options={
                'unique_together': {('assess_patientID', 'assess_questionnaireID', 'start')},
            },
        ),
    ]
