# Generated by Django 3.0.3 on 2020-02-08 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patients', '0001_initial'),
        ('Questions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Response',
            new_name='QuestionResponse',
        ),
        migrations.AlterModelTable(
            name='questionresponse',
            table='Response',
        ),
    ]
