# Generated by Django 3.0.3 on 2020-03-16 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientassessment',
            name='last_answered_qn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Questions.Questions'),
        ),
        # manually added
        migrations.AddField(
            model_name='questionnaire',
            name='questionnaireType',
            field=models.CharField(default='default', max_length=45, verbose_name='questionnaire_type'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='questionresponse',
            unique_together={},
            # unique_together={('patientID', 'questionID', 'answerID', 'text', 'questionnaireID', 'date')},
        ),
    ]
