# Generated by Django 3.0.3 on 2020-03-16 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0002_patientassessment_last_answered_qn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='active_flag',
            field=models.IntegerField(choices=[(1, 'True'), (0, 'False')], default=0, verbose_name='active_flag'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='questionnaireType',
            field=models.CharField(choices=[('MOBILITY', 'Mobility Questionnaire'), ('VISION', 'Vision Questionnaire'), ('HEARING', 'Hearing Questionnaire'), ('HOUSEHOLD', 'Household Questionnaire'), ('PATIENT_INFO', 'Patient Registration Questionnaire')], max_length=45, verbose_name='questionnaire_type'),
        ),
    ]
