# Generated by Django 3.0.3 on 2020-02-09 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0002_auto_20200208_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logic',
            name='rel_ID',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='relationID'),
        ),
    ]
