# Generated by Django 3.0.3 on 2020-03-16 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0003_auto_20200316_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='questionnaireType',
            field=models.CharField(choices=[('MOBILITY', 'Mobility Questionnaire'), ('VISION', 'Vision Questionnaire'), ('HEARING', 'Hearing Questionnaire'), ('WASHINGTON', 'General Questionnaire'), ('HOUSEHOLD', 'Household Questionnaire'), ('PATIENT_INFO', 'Patient Registration Questionnaire')], max_length=45, verbose_name='questionnaire_type'),
        ),
    ]
