# Generated by Django 3.0.3 on 2020-02-09 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0003_auto_20200209_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logic',
            name='rel_ans_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Questions.Answer'),
        ),
    ]
