# Generated by Django 3.0.3 on 2020-02-09 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0004_auto_20200209_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logic',
            name='next_qID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_qID', to='Questions.Questions'),
        ),
        migrations.AlterField(
            model_name='logic',
            name='rel_ID',
            field=models.IntegerField(null=True, unique=True, verbose_name='relationID'),
        ),
        migrations.AlterField(
            model_name='logic',
            name='rel_ans_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Questions.Answer'),
        ),
    ]
