# Generated by Django 3.0.3 on 2020-02-24 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0005_auto_20200209_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logic',
            name='rel_type',
            field=models.CharField(blank=True, choices=[('INSEQ', 'In Sequence'), ('NEXT', 'Next'), ('AND', 'And'), ('OR', 'Or')], max_length=10),
        ),
    ]
