# Generated by Django 3.0.3 on 2020-02-29 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patients', '0001_initial'),
        ('Questions', '0006_auto_20200224_1722'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='patientassessment',
            unique_together={('assess_patientID', 'assess_questionnaireID', 'start')},
        ),
    ]
