# Generated by Django 3.0.3 on 2020-03-17 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0006_auto_20200317_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionresponse',
            name='text',
            field=models.CharField(blank=True, max_length=300, verbose_name='text'),
        ),
    ]
