# Generated by Django 3.0.3 on 2020-03-17 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0007_auto_20200317_1922'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='questionresponse',
            unique_together=set(),
        ),
        migrations.AlterModelTable(
            name='questionresponse',
            table=None,
        ),
    ]
