# Generated by Django 3.0.3 on 2020-03-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(blank=True, max_length=255)),
                ('expires_on', models.DateTimeField(null=True)),
                ('expired', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('key', models.CharField(max_length=255)),
                ('secret', models.CharField(max_length=255)),
            ],
        ),
    ]
