# Generated by Django 3.0.3 on 2020-03-07 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('locationID', models.AutoField(default=0, primary_key=True, serialize=False, verbose_name='locationID')),
                ('locationName', models.CharField(max_length=45, verbose_name='locationName')),
                ('parentLocID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Locations.Location', verbose_name='parentLocationID')),
            ],
        ),
        migrations.CreateModel(
            name='HouseHold',
            fields=[
                ('householdID', models.CharField(max_length=35, primary_key=True, serialize=False, verbose_name='householdID')),
                ('date', models.CharField(max_length=35)),
                ('village_name', models.CharField(blank=True, max_length=100, verbose_name='village_name')),
                ('street_name', models.CharField(blank=True, max_length=100, verbose_name='street_name')),
                ('gps', models.CharField(max_length=70, verbose_name='gps')),
                ('availability', models.IntegerField(default=1, verbose_name='availability')),
                ('reason_refusal', models.CharField(blank=True, max_length=500, null=True, verbose_name='reasonforrefusal')),
                ('visit_num', models.IntegerField(blank=True, verbose_name='visit_num')),
                ('key_informer', models.CharField(max_length=45, verbose_name='key_informer')),
                ('tel1_num', models.CharField(blank=True, max_length=30, verbose_name='tel1_num')),
                ('tel1_owner', models.CharField(blank=True, max_length=45, verbose_name='tel1_owner')),
                ('tel2_num', models.CharField(blank=True, max_length=30, verbose_name='tel2_num')),
                ('tel2_owner', models.CharField(blank=True, max_length=45, verbose_name='tel2_owner')),
                ('consent', models.CharField(max_length=30, verbose_name='consent')),
                ('a2q1', models.CharField(max_length=30, verbose_name='a2q1')),
                ('a2q2', models.CharField(max_length=30, verbose_name='a2q2')),
                ('a2q3', models.CharField(max_length=30, verbose_name='a2q3')),
                ('a2q4', models.CharField(max_length=30, verbose_name='a2q4')),
                ('a2q5', models.CharField(max_length=30, verbose_name='a2q5')),
                ('a2q6', models.CharField(max_length=30, verbose_name='a2q6')),
                ('a2q7', models.CharField(max_length=30, verbose_name='a2q7')),
                ('a2q8', models.CharField(max_length=30, verbose_name='a2q8')),
                ('a2q9', models.CharField(max_length=30, verbose_name='a2q9')),
                ('a2q10', models.CharField(max_length=30, verbose_name='a2q10')),
                ('a2q11', models.CharField(max_length=30, verbose_name='a2q11')),
                ('a2q12', models.CharField(max_length=30, verbose_name='a2q12')),
                ('a2q13', models.CharField(max_length=30, verbose_name='a2q13')),
                ('enumeratorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.Enumerator', verbose_name='enumeratorID')),
                ('parentLocID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Locations.Location', verbose_name='clusterID')),
            ],
        ),
    ]
