# Generated by Django 3.0.3 on 2020-03-10 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Locations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='household',
            old_name='gps',
            new_name='gps_latitude',
        ),
        migrations.RemoveField(
            model_name='household',
            name='street_name',
        ),
        migrations.RemoveField(
            model_name='household',
            name='village_name',
        ),
        migrations.AddField(
            model_name='household',
            name='gps_longitude',
            field=models.CharField(default='default', max_length=70, verbose_name='gps'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='household',
            name='village_street_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='village_street_name'),
        ),
        migrations.AlterField(
            model_name='household',
            name='availability',
            field=models.CharField(max_length=70, verbose_name='availability'),
        ),
    ]
