# Generated by Django 3.0.3 on 2020-03-17 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20200312_1027'),
        ('Locations', '0002_auto_20200310_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='enumeratorID',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='Users.Enumerator', verbose_name='enumeratorID'),
        ),
    ]
