# Generated by Django 3.0.3 on 2020-03-17 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Locations', '0003_auto_20200317_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='parentLocID',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Locations.Location', verbose_name='parentLocationID'),
        ),
    ]
