# Generated by Django 3.0.3 on 2020-03-17 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patients', '0002_auto_20200317_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.CharField(max_length=35, verbose_name='date_of_birth'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='deceased_date',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='deceased_date'),
        ),
    ]
