# Generated by Django 3.0.3 on 2020-03-07 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('questionServicesID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questions.Questions')),
                ('questionnaireID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questions.Questionnaire')),
            ],
            options={
                'unique_together': {('questionServicesID', 'questionnaireID')},
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('questionDiagnosisID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questions.Questions')),
                ('questionnaireID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questions.Questionnaire')),
            ],
            options={
                'unique_together': {('questionDiagnosisID', 'questionnaireID')},
            },
        ),
        migrations.CreateModel(
            name='Cause',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('questionCauseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questions.Questions')),
                ('questionnaireID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questions.Questionnaire')),
            ],
            options={
                'unique_together': {('questionCauseID', 'questionnaireID')},
            },
        ),
        migrations.CreateModel(
            name='AssistiveTechnology',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('questionTechnologyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questions.Questions')),
                ('questionnaireID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questions.Questionnaire')),
            ],
            options={
                'unique_together': {('questionTechnologyID', 'questionnaireID')},
            },
        ),
    ]
